// Code generated by protoc-gen-go. DO NOT EDIT.
// source: myFile.proto

/*
Package hello is a generated protocol buffer package.

It is generated from these files:
	myFile.proto

It has these top-level messages:
	MessageReq
	Empty
*/
package hello

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageReq struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Text string `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
}

func (m *MessageReq) Reset()                    { *m = MessageReq{} }
func (m *MessageReq) String() string            { return proto.CompactTextString(m) }
func (*MessageReq) ProtoMessage()               {}
func (*MessageReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MessageReq) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *MessageReq) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*MessageReq)(nil), "hello.MessageReq")
	proto.RegisterType((*Empty)(nil), "hello.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Notificator service

type NotificatorClient interface {
	SendMessage(ctx context.Context, in *MessageReq, opts ...grpc.CallOption) (*Empty, error)
}

type notificatorClient struct {
	cc *grpc.ClientConn
}

func NewNotificatorClient(cc *grpc.ClientConn) NotificatorClient {
	return &notificatorClient{cc}
}

func (c *notificatorClient) SendMessage(ctx context.Context, in *MessageReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/hello.Notificator/SendMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Notificator service

type NotificatorServer interface {
	SendMessage(context.Context, *MessageReq) (*Empty, error)
}

func RegisterNotificatorServer(s *grpc.Server, srv NotificatorServer) {
	s.RegisterService(&_Notificator_serviceDesc, srv)
}

func _Notificator_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificatorServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.Notificator/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificatorServer).SendMessage(ctx, req.(*MessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Notificator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hello.Notificator",
	HandlerType: (*NotificatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _Notificator_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "myFile.proto",
}

func init() { proto.RegisterFile("myFile.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xad, 0x74, 0xcb,
	0xcc, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0x48, 0xcd, 0xc9, 0xc9, 0x57,
	0x32, 0xe1, 0xe2, 0xf2, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x0d, 0x4a, 0x2d, 0x14, 0x12, 0xe2,
	0x62, 0x29, 0xa9, 0x2c, 0x48, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0xc1, 0x62,
	0xa9, 0x15, 0x25, 0x12, 0x4c, 0x50, 0xb1, 0xd4, 0x8a, 0x12, 0x25, 0x76, 0x2e, 0x56, 0xd7, 0xdc,
	0x82, 0x92, 0x4a, 0x23, 0x7b, 0x2e, 0x6e, 0xbf, 0xfc, 0x92, 0xcc, 0xb4, 0xcc, 0xe4, 0xc4, 0x92,
	0xfc, 0x22, 0x21, 0x03, 0x2e, 0xee, 0xe0, 0xd4, 0xbc, 0x14, 0xa8, 0x89, 0x42, 0x82, 0x7a, 0x60,
	0x4b, 0xf4, 0x10, 0x36, 0x48, 0xf1, 0x40, 0x85, 0xc0, 0xda, 0x95, 0x18, 0x92, 0xd8, 0xc0, 0xae,
	0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x5e, 0xf7, 0x98, 0xea, 0x9d, 0x00, 0x00, 0x00,
}
